prometheus:
  server:
    version: 1.1.3.linux-amd64
    install_dir: /opt
    source: https://github.com/prometheus/prometheus/releases/download/v1.1.3/prometheus-1.1.3.linux-amd64.tar.gz
    source_hash: md5=839293afa9bfce47c476a0bdfd01a780
    args:
      config_file: /etc/prometheus/prometheus.yml
      storage:
        local_path: /var/lib/prometheus/metrics
    config:
      global:
        scrape_interval: 15s
        evaluation_interval: 15s
      scrape_configs:
        - job_name: 'prometheus'
          scrape_interval: 5s
          static_configs:
            - targets: ['localhost:9090']
        - job_name: 'node'
          scrape_interval: 5s
          static_configs:
            - targets: ['localhost:9100']
  alertmanager:
    version: 0.4.2.linux-amd64
    install_dir: /opt
    source: https://github.com/prometheus/alertmanager/releases/download/v0.4.2/alertmanager-0.4.2.linux-amd64.tar.gz
    source_hash: md5=715878f14ab091769c989ecdb2db9f15
    args:
      config_file: /etc/alertmanager/alertmanager.yml
      storage:
        path: /var/lib/alertmanager
    config:
      global:
        smtp_smarthost: "localhost:25"
        smtp_from: 'alertmanager@example.org'
        smtp_auth_username: 'alertmanager'
        smtp_auth_password: 'password'
      templates:
        - "/etc/alertmanager/template/*.tmpl"
      route:
        group_by: ['alertname', 'cluster', 'service']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 3h
        receiver: team-X-mails
        routes:
        - match_re:
            service: ^(foo1|foo2|baz)$
          receiver: team-X-mails
      inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'cluster', 'service']
      receivers:
      - name: 'team-X-mails'
        email_configs:
        - to: 'team-X+alerts@example.org'
  exporters:
    node:
      version: 0.12.0.linux-amd64
      install_dir: /opt
      source: https://github.com/prometheus/node_exporter/releases/download/0.12.0/node_exporter-0.12.0.linux-amd64.tar.gz
      source_hash: md5=efe49b6fae4b1a5cb75b24a60a35e1fc
