prometheus:
  server:
    version: 1.4.1.linux-amd64
    install_dir: /opt
    source: 'https://github.com/prometheu4/prometheus/releases/download/v1.4.1/prometheus-1.4.1.linux-amd64.tar.gz'
    source_hash: sha1=3e78173e7d65623e79e0292da16e6155de947185
    args:
      config_file: /etc/prometheus/prometheus.yml
      storage:
        local_path: /var/lib/prometheus/metrics
  alertmanager:
    version: 0.5.1.linux-amd64
    install_dir: /opt
    source: https://github.com/prometheus/alertmanager/releases/download/v0.5.1/alertmanager-0.5.1.linux-amd64.tar.gz
    source_hash: sha1=8f82ccc0db806991256084faee9335353d8e3f0d
    args:
      config_file: /etc/alertmanager/alertmanager.yml
      storage:
        path: /var/lib/alertmanager
  exporters:
    node:
      version: 0.13.0.linux-amd64
      install_dir: /opt
      source: https://github.com/prometheus/node_exporter/releases/download/v0.13.0/node_exporter-0.13.0.linux-amd64.tar.gz
      source_hash: sha1=84ca5f711962319f6f7823208b9d867ab1c0e3e7
